version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_default_openai_api_key}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - .:/code
    networks:
      - app-network
    restart: always

  redis:
    image: redis:latest
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
